FROM node:20-alpine AS base
WORKDIR /app
COPY package.json ./
RUN npm install --omit=dev

FROM base AS builder
WORKDIR /app
COPY . .
RUN npm install

FROM base
WORKDIR /app
COPY --from=builder /app .
EXPOSE ${PORT:-8081}
CMD ["node", "server-local.js"]
